# Generated by Django 4.0.1 on 2022-06-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_blood_model',
            name='user',
        ),
    ]
