# Generated by Django 4.0.1 on 2022-06-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_order_blood_model_user_n'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='received_unit',
            new_name='Received_unit_model',
        ),
    ]
